[shared_memory]
name = "custom_memory"
slot_size = 2048
slot_count = 100

[logging]
log_path = "./logs"
file_prefix = "workers"
console_output = true
level = "debug"

[http]
port = 9090
bind_address = "0.0.0.0"
timeout_seconds = 30
max_connections = 1000

[queue]
capacity = 100
name = "task_queue"
persistent = false
