### GET request to example server
GET http://localhost:8080/hello

###

GET http://localhost:8080/status

###

# curl -X POST http://localhost:8080/send -H "Content-Type: application/json" -d "{\"message\": \"Hello from HTTP client\", \"data\": {\"test\": \"value\"}}"
POST http://localhost:8080/send
Content-Type: application/json

{
  "message": "Hello from HTTP client",
  "data": {
    "test": "value"
  }
}

###



# curl -X POST http://localhost:8888/api/test
#  -H "Content-Type: application/json"
#-H "Authorization: Bearer test-token"
#-d '{"message": "Hello World"}'
POST http://localhost:8888/api/test11
Authorization: Bearer test-token
Content-Type: application/json

{
  "message": "Hello World"
}

###

