[package]
name = "entry"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "MI7 跨进程消息队列生产者"

[[bin]]
name = "entry"
path = "src/main.rs"

[dependencies]
ipc_queue.workspace = true
tokio.workspace = true